{
	"document": {
		"aggregate_severity": {
			"namespace": "https://access.redhat.com/security/updates/classification/",
			"text": "Moderate"
		},
		"category": "csaf_vex",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright Â© Red Hat, Inc. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "An update for python-idna is now available for Red Hat Enterprise Linux 8.6.\n\nRed Hat Product Security has rated this update as having a security impact of\nModerate. A Common Vulnerability Scoring System (CVSS) base score, which gives a detailed severity rating, is available for each vulnerability from the CVE\nlink(s) in the References section.",
				"title": "Topic"
			},
			{
				"category": "general",
				"text": "Security Fix(es):\n\n* python-idna: potential DoS via resource consumption via specially crafted\ninputs to idna.encode() (CVE-2024-3651)",
				"title": "Details"
			},
			{
				"category": "legal_disclaimer",
				"text": "This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original.",
				"title": "Terms of Use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://access.redhat.com/security/team/contact/",
			"issuing_authority": "Red Hat Product Security is responsible for vulnerability handling across all Red Hat offerings.",
			"name": "Red Hat Product Security",
			"namespace": "https://www.redhat.com"
		},
		"references": [
			{
				"category": "self",
				"summary": "https://access.redhat.com/errata/RHSA-2024:3552",
				"url": "https://access.redhat.com/errata/RHSA-2024:3552"
			},
			{
				"category": "external",
				"summary": "https://access.redhat.com/security/updates/classification/#moderate",
				"url": "https://access.redhat.com/security/updates/classification/#moderate"
			},
			{
				"category": "external",
				"summary": "2274779",
				"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2274779"
			},
			{
				"category": "self",
				"summary": "Canonical URL",
				"url": "https://access.redhat.com/security/data/csaf/v2/advisories/2024/rhsa-2024_3552.json"
			}
		],
		"title": "Red Hat Security Advisory: python-idna security and bug fix update",
		"tracking": {
			"current_release_date": "2024-08-15T12:46:06+00:00",
			"generator": {
				"date": "2024-08-15T12:46:06+00:00",
				"engine": {
					"name": "Red Hat SDEngine",
					"version": "3.32.0"
				}
			},
			"id": "RHSA-2024:3552",
			"initial_release_date": "2024-06-03T15:47:46+00:00",
			"revision_history": [
				{
					"date": "2024-06-03T15:47:46+00:00",
					"number": "1",
					"summary": "Initial version"
				},
				{
					"date": "2024-06-03T15:47:46+00:00",
					"number": "2",
					"summary": "Last updated version"
				},
				{
					"date": "2024-08-15T12:46:06+00:00",
					"number": "3",
					"summary": "Last generated version"
				}
			],
			"status": "final",
			"version": "3"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_name",
								"name": "Red Hat Enterprise Linux BaseOS E4S (v.8.6)",
								"product": {
									"name": "Red Hat Enterprise Linux BaseOS E4S (v.8.6)",
									"product_id": "BaseOS-8.6.0.Z.E4S",
									"product_identification_helper": {
										"cpe": "cpe:/o:redhat:rhel_e4s:8.6::baseos"
									}
								}
							},
							{
								"category": "product_name",
								"name": "Red Hat Enterprise Linux BaseOS TUS (v.8.6)",
								"product": {
									"name": "Red Hat Enterprise Linux BaseOS TUS (v.8.6)",
									"product_id": "BaseOS-8.6.0.Z.TUS",
									"product_identification_helper": {
										"cpe": "cpe:/o:redhat:rhel_tus:8.6::baseos"
									}
								}
							},
							{
								"category": "product_name",
								"name": "Red Hat Enterprise Linux BaseOS AUS (v.8.6)",
								"product": {
									"name": "Red Hat Enterprise Linux BaseOS AUS (v.8.6)",
									"product_id": "BaseOS-8.6.0.Z.AUS",
									"product_identification_helper": {
										"cpe": "cpe:/o:redhat:rhel_aus:8.6::baseos"
									}
								}
							}
						],
						"category": "product_family",
						"name": "Red Hat Enterprise Linux"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-idna-0:2.5-5.el8_6.1.src",
								"product": {
									"name": "python-idna-0:2.5-5.el8_6.1.src",
									"product_id": "python-idna-0:2.5-5.el8_6.1.src",
									"product_identification_helper": {
										"purl": "pkg:rpm/redhat/python-idna@2.5-5.el8_6.1?arch=src"
									}
								}
							}
						],
						"category": "architecture",
						"name": "src"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python3-idna-0:2.5-5.el8_6.1.noarch",
								"product": {
									"name": "python3-idna-0:2.5-5.el8_6.1.noarch",
									"product_id": "python3-idna-0:2.5-5.el8_6.1.noarch",
									"product_identification_helper": {
										"purl": "pkg:rpm/redhat/python3-idna@2.5-5.el8_6.1?arch=noarch"
									}
								}
							}
						],
						"category": "architecture",
						"name": "noarch"
					}
				],
				"category": "vendor",
				"name": "Red Hat"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-idna-0:2.5-5.el8_6.1.src as a component of Red Hat Enterprise Linux BaseOS AUS (v.8.6)",
					"product_id": "BaseOS-8.6.0.Z.AUS:python-idna-0:2.5-5.el8_6.1.src"
				},
				"product_reference": "python-idna-0:2.5-5.el8_6.1.src",
				"relates_to_product_reference": "BaseOS-8.6.0.Z.AUS"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python3-idna-0:2.5-5.el8_6.1.noarch as a component of Red Hat Enterprise Linux BaseOS AUS (v.8.6)",
					"product_id": "BaseOS-8.6.0.Z.AUS:python3-idna-0:2.5-5.el8_6.1.noarch"
				},
				"product_reference": "python3-idna-0:2.5-5.el8_6.1.noarch",
				"relates_to_product_reference": "BaseOS-8.6.0.Z.AUS"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-idna-0:2.5-5.el8_6.1.src as a component of Red Hat Enterprise Linux BaseOS E4S (v.8.6)",
					"product_id": "BaseOS-8.6.0.Z.E4S:python-idna-0:2.5-5.el8_6.1.src"
				},
				"product_reference": "python-idna-0:2.5-5.el8_6.1.src",
				"relates_to_product_reference": "BaseOS-8.6.0.Z.E4S"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python3-idna-0:2.5-5.el8_6.1.noarch as a component of Red Hat Enterprise Linux BaseOS E4S (v.8.6)",
					"product_id": "BaseOS-8.6.0.Z.E4S:python3-idna-0:2.5-5.el8_6.1.noarch"
				},
				"product_reference": "python3-idna-0:2.5-5.el8_6.1.noarch",
				"relates_to_product_reference": "BaseOS-8.6.0.Z.E4S"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-idna-0:2.5-5.el8_6.1.src as a component of Red Hat Enterprise Linux BaseOS TUS (v.8.6)",
					"product_id": "BaseOS-8.6.0.Z.TUS:python-idna-0:2.5-5.el8_6.1.src"
				},
				"product_reference": "python-idna-0:2.5-5.el8_6.1.src",
				"relates_to_product_reference": "BaseOS-8.6.0.Z.TUS"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python3-idna-0:2.5-5.el8_6.1.noarch as a component of Red Hat Enterprise Linux BaseOS TUS (v.8.6)",
					"product_id": "BaseOS-8.6.0.Z.TUS:python3-idna-0:2.5-5.el8_6.1.noarch"
				},
				"product_reference": "python3-idna-0:2.5-5.el8_6.1.noarch",
				"relates_to_product_reference": "BaseOS-8.6.0.Z.TUS"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2024-3651",
			"cwe": {
				"id": "CWE-400",
				"name": "Uncontrolled Resource Consumption"
			},
			"discovery_date": "2024-04-12T00:00:00+00:00",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "2274779"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "A flaw was found in the python-idna library. A malicious argument was sent to the idna.encode() function can trigger an uncontrolled resource consumption, resulting in a denial of service.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "python-idna: potential DoS via resource consumption via specially crafted inputs to idna.encode()",
					"title": "Vulnerability summary"
				},
				{
					"category": "other",
					"text": "The vulnerability in the idna.encode() function, allowing for resource consumption via specially crafted arguments, is categorized as a moderate severity issue due to its potential impact on system availability rather than data integrity or confidentiality. While the vulnerability can lead to a denial-of-service condition, it requires the passing of unusually large or maliciously crafted inputs to exploit. Normal usage scenarios typically do not encounter such inputs.",
					"title": "Statement"
				},
				{
					"category": "general",
					"text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
					"title": "CVSS score applicability"
				}
			],
			"product_status": {
				"fixed": [
					"BaseOS-8.6.0.Z.AUS:python-idna-0:2.5-5.el8_6.1.src",
					"BaseOS-8.6.0.Z.AUS:python3-idna-0:2.5-5.el8_6.1.noarch",
					"BaseOS-8.6.0.Z.E4S:python-idna-0:2.5-5.el8_6.1.src",
					"BaseOS-8.6.0.Z.E4S:python3-idna-0:2.5-5.el8_6.1.noarch",
					"BaseOS-8.6.0.Z.TUS:python-idna-0:2.5-5.el8_6.1.src",
					"BaseOS-8.6.0.Z.TUS:python3-idna-0:2.5-5.el8_6.1.noarch"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2024-3651"
				},
				{
					"category": "external",
					"summary": "RHBZ#2274779",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2274779"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2024-3651",
					"url": "https://www.cve.org/CVERecord?id=CVE-2024-3651"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2024-3651",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2024-3651"
				}
			],
			"release_date": "2024-04-12T00:00:00+00:00",
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "Before applying this update, make sure all previously released errata\nrelevant to your system have been applied.\n\nFor details on how to apply this update, refer to:\n\nhttps://access.redhat.com/articles/11258",
					"product_ids": [
						"BaseOS-8.6.0.Z.AUS:python-idna-0:2.5-5.el8_6.1.src",
						"BaseOS-8.6.0.Z.AUS:python3-idna-0:2.5-5.el8_6.1.noarch",
						"BaseOS-8.6.0.Z.E4S:python-idna-0:2.5-5.el8_6.1.src",
						"BaseOS-8.6.0.Z.E4S:python3-idna-0:2.5-5.el8_6.1.noarch",
						"BaseOS-8.6.0.Z.TUS:python-idna-0:2.5-5.el8_6.1.src",
						"BaseOS-8.6.0.Z.TUS:python3-idna-0:2.5-5.el8_6.1.noarch"
					],
					"restart_required": {
						"category": "none"
					},
					"url": "https://access.redhat.com/errata/RHSA-2024:3552"
				},
				{
					"category": "workaround",
					"details": "Mitigation for this issue is either not available or the currently available options don't meet the Red Hat Product Security criteria comprising ease of use and deployment, applicability to widespread installation base or stability.",
					"product_ids": [
						"BaseOS-8.6.0.Z.AUS:python-idna-0:2.5-5.el8_6.1.src",
						"BaseOS-8.6.0.Z.AUS:python3-idna-0:2.5-5.el8_6.1.noarch",
						"BaseOS-8.6.0.Z.E4S:python-idna-0:2.5-5.el8_6.1.src",
						"BaseOS-8.6.0.Z.E4S:python3-idna-0:2.5-5.el8_6.1.noarch",
						"BaseOS-8.6.0.Z.TUS:python-idna-0:2.5-5.el8_6.1.src",
						"BaseOS-8.6.0.Z.TUS:python3-idna-0:2.5-5.el8_6.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"attackComplexity": "LOW",
						"attackVector": "NETWORK",
						"availabilityImpact": "HIGH",
						"baseScore": 6.5,
						"baseSeverity": "MEDIUM",
						"confidentialityImpact": "NONE",
						"integrityImpact": "NONE",
						"privilegesRequired": "LOW",
						"scope": "UNCHANGED",
						"userInteraction": "NONE",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
						"version": "3.1"
					},
					"products": [
						"BaseOS-8.6.0.Z.AUS:python-idna-0:2.5-5.el8_6.1.src",
						"BaseOS-8.6.0.Z.AUS:python3-idna-0:2.5-5.el8_6.1.noarch",
						"BaseOS-8.6.0.Z.E4S:python-idna-0:2.5-5.el8_6.1.src",
						"BaseOS-8.6.0.Z.E4S:python3-idna-0:2.5-5.el8_6.1.noarch",
						"BaseOS-8.6.0.Z.TUS:python-idna-0:2.5-5.el8_6.1.src",
						"BaseOS-8.6.0.Z.TUS:python3-idna-0:2.5-5.el8_6.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Moderate"
				}
			],
			"title": "python-idna: potential DoS via resource consumption via specially crafted inputs to idna.encode()"
		}
	]
}
