{
	"document": {
		"aggregate_severity": {
			"namespace": "https://access.redhat.com/security/updates/classification/",
			"text": "Moderate"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright Â© Red Hat, Inc. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "An update for python-dns is now available for Red Hat Enterprise Linux 9.\n\nRed Hat Product Security has rated this update as having a security impact of Moderate. A Common Vulnerability Scoring System (CVSS) base score, which gives a detailed severity rating, is available for each vulnerability from the CVE link(s) in the References section.",
				"title": "Topic"
			},
			{
				"category": "general",
				"text": "The python-dns package contains the dnslib module that implements a DNS client and additional modules that define certain symbolic constants used by DNS, such as dnstype, dnsclass and dnsopcode.\n\nSecurity Fix(es):\n\n* dnspython: denial of service in stub resolver (CVE-2023-29483)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.\n\nAdditional Changes:\n\nFor detailed information on changes in this release, see the Red Hat Enterprise Linux 9.5 Release Notes linked from the References section.",
				"title": "Details"
			},
			{
				"category": "legal_disclaimer",
				"text": "This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original.",
				"title": "Terms of Use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://access.redhat.com/security/team/contact/",
			"issuing_authority": "Red Hat Product Security is responsible for vulnerability handling across all Red Hat products and services.",
			"name": "Red Hat Product Security",
			"namespace": "https://www.redhat.com"
		},
		"references": [
			{
				"category": "self",
				"summary": "https://access.redhat.com/errata/RHSA-2024:9423",
				"url": "https://access.redhat.com/errata/RHSA-2024:9423"
			},
			{
				"category": "external",
				"summary": "https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/9.5_release_notes/index",
				"url": "https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/9.5_release_notes/index"
			},
			{
				"category": "external",
				"summary": "https://access.redhat.com/security/updates/classification/#moderate",
				"url": "https://access.redhat.com/security/updates/classification/#moderate"
			},
			{
				"category": "external",
				"summary": "2274520",
				"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2274520"
			},
			{
				"category": "external",
				"summary": "RHEL-32663",
				"url": "https://issues.redhat.com/browse/RHEL-32663"
			},
			{
				"category": "self",
				"summary": "Canonical URL",
				"url": "https://security.access.redhat.com/data/csaf/v2/advisories/2024/rhsa-2024_9423.json"
			}
		],
		"title": "Red Hat Security Advisory: python-dns security update",
		"tracking": {
			"current_release_date": "2024-11-24T11:40:35+00:00",
			"generator": {
				"date": "2024-11-24T11:40:35+00:00",
				"engine": {
					"name": "Red Hat SDEngine",
					"version": "4.2.1"
				}
			},
			"id": "RHSA-2024:9423",
			"initial_release_date": "2024-11-12T09:22:42+00:00",
			"revision_history": [
				{
					"date": "2024-11-12T09:22:42+00:00",
					"number": "1",
					"summary": "Initial version"
				},
				{
					"date": "2024-11-12T09:22:42+00:00",
					"number": "2",
					"summary": "Last updated version"
				},
				{
					"date": "2024-11-24T11:40:35+00:00",
					"number": "3",
					"summary": "Last generated version"
				}
			],
			"status": "final",
			"version": "3"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_name",
								"name": "Red Hat Enterprise Linux BaseOS (v. 9)",
								"product": {
									"name": "Red Hat Enterprise Linux BaseOS (v. 9)",
									"product_id": "BaseOS-9.5.0.GA",
									"product_identification_helper": {
										"cpe": "cpe:/o:redhat:enterprise_linux:9::baseos"
									}
								}
							}
						],
						"category": "product_family",
						"name": "Red Hat Enterprise Linux"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-dns-0:2.6.1-3.el9.src",
								"product": {
									"name": "python-dns-0:2.6.1-3.el9.src",
									"product_id": "python-dns-0:2.6.1-3.el9.src",
									"product_identification_helper": {
										"purl": "pkg:rpm/redhat/python-dns@2.6.1-3.el9?arch=src"
									}
								}
							}
						],
						"category": "architecture",
						"name": "src"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python3-dns-0:2.6.1-3.el9.noarch",
								"product": {
									"name": "python3-dns-0:2.6.1-3.el9.noarch",
									"product_id": "python3-dns-0:2.6.1-3.el9.noarch",
									"product_identification_helper": {
										"purl": "pkg:rpm/redhat/python3-dns@2.6.1-3.el9?arch=noarch"
									}
								}
							}
						],
						"category": "architecture",
						"name": "noarch"
					}
				],
				"category": "vendor",
				"name": "Red Hat"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-dns-0:2.6.1-3.el9.src as a component of Red Hat Enterprise Linux BaseOS (v. 9)",
					"product_id": "BaseOS-9.5.0.GA:python-dns-0:2.6.1-3.el9.src"
				},
				"product_reference": "python-dns-0:2.6.1-3.el9.src",
				"relates_to_product_reference": "BaseOS-9.5.0.GA"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python3-dns-0:2.6.1-3.el9.noarch as a component of Red Hat Enterprise Linux BaseOS (v. 9)",
					"product_id": "BaseOS-9.5.0.GA:python3-dns-0:2.6.1-3.el9.noarch"
				},
				"product_reference": "python3-dns-0:2.6.1-3.el9.noarch",
				"relates_to_product_reference": "BaseOS-9.5.0.GA"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2023-29483",
			"cwe": {
				"id": "CWE-696",
				"name": "Incorrect Behavior Order"
			},
			"discovery_date": "2024-04-11T00:00:00+00:00",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "2274520"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "The dnspython stub resolver is vulnerable to a denial of service (DoS) risk if an attacker sends a malicious response forged with the correct address and port before a legitimate one arrives on the UDP port used by dnspython for the query. In such cases, dnspython could either switch to another resolver or abandon the query altogether, potentially leading to service denial for that resolution.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "dnspython: denial of service in stub resolver",
					"title": "Vulnerability summary"
				},
				{
					"category": "other",
					"text": "The vulnerability in dnspython where it may accept a malicious DNS response over a legitimate one due to timing issues poses a moderate severity risk. While the impact is limited to potential denial of service for DNS resolution requests, it requires precise timing and the ability to send malicious responses before legitimate ones arrive. This attack vector relies on the attacker's ability to predict or manipulate the timing of DNS responses, making it more complex to exploit compared to other vulnerabilities. However, if successfully exploited, it can disrupt DNS resolution services, affecting the availability of the targeted domain or service.",
					"title": "Statement"
				},
				{
					"category": "general",
					"text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
					"title": "CVSS score applicability"
				}
			],
			"product_status": {
				"fixed": [
					"BaseOS-9.5.0.GA:python-dns-0:2.6.1-3.el9.src",
					"BaseOS-9.5.0.GA:python3-dns-0:2.6.1-3.el9.noarch"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2023-29483"
				},
				{
					"category": "external",
					"summary": "RHBZ#2274520",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2274520"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2023-29483",
					"url": "https://www.cve.org/CVERecord?id=CVE-2023-29483"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2023-29483",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2023-29483"
				},
				{
					"category": "external",
					"summary": "https://www.dnspython.org/news/2.6.0rc1/",
					"url": "https://www.dnspython.org/news/2.6.0rc1/"
				}
			],
			"release_date": "2024-02-09T00:00:00+00:00",
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "For details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258",
					"product_ids": [
						"BaseOS-9.5.0.GA:python-dns-0:2.6.1-3.el9.src",
						"BaseOS-9.5.0.GA:python3-dns-0:2.6.1-3.el9.noarch"
					],
					"restart_required": {
						"category": "none"
					},
					"url": "https://access.redhat.com/errata/RHSA-2024:9423"
				},
				{
					"category": "workaround",
					"details": "Mitigation for this issue is either not available or the currently available options don't meet the Red Hat Product Security criteria comprising ease of use and deployment, applicability to widespread installation base or stability.",
					"product_ids": [
						"BaseOS-9.5.0.GA:python-dns-0:2.6.1-3.el9.src",
						"BaseOS-9.5.0.GA:python3-dns-0:2.6.1-3.el9.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"attackComplexity": "HIGH",
						"attackVector": "NETWORK",
						"availabilityImpact": "HIGH",
						"baseScore": 5.9,
						"baseSeverity": "MEDIUM",
						"confidentialityImpact": "NONE",
						"integrityImpact": "NONE",
						"privilegesRequired": "NONE",
						"scope": "UNCHANGED",
						"userInteraction": "NONE",
						"vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"version": "3.1"
					},
					"products": [
						"BaseOS-9.5.0.GA:python-dns-0:2.6.1-3.el9.src",
						"BaseOS-9.5.0.GA:python3-dns-0:2.6.1-3.el9.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Moderate"
				}
			],
			"title": "dnspython: denial of service in stub resolver"
		}
	]
}
