{
	"document": {
		"aggregate_severity": {
			"namespace": "https://access.redhat.com/security/updates/classification/",
			"text": "Moderate"
		},
		"category": "csaf_vex",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright Â© Red Hat, Inc. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "An update for python-urllib3 is now available for Red Hat Enterprise Linux 8.\n\nRed Hat Product Security has rated this update as having a security impact of Moderate. A Common Vulnerability Scoring System (CVSS) base score, which gives a detailed severity rating, is available for each vulnerability from the CVE link(s) in the References section.",
				"title": "Topic"
			},
			{
				"category": "general",
				"text": "The python-urllib3 package provides the Python HTTP module with connection pooling and file POST abilities.\n\nSecurity Fix(es):\n\n* python-urllib3: CRLF injection due to not encoding the '\\r\\n' sequence leading to possible attack on internal service (CVE-2019-11236)\n\n* python-urllib3: Certification mishandle when error should be thrown (CVE-2019-11324)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.\n\nAdditional Changes:\n\nFor detailed information on changes in this release, see the Red Hat Enterprise Linux 8.1 Release Notes linked from the References section.",
				"title": "Details"
			},
			{
				"category": "legal_disclaimer",
				"text": "This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original.",
				"title": "Terms of Use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://access.redhat.com/security/team/contact/",
			"issuing_authority": "Red Hat Product Security is responsible for vulnerability handling across all Red Hat offerings.",
			"name": "Red Hat Product Security",
			"namespace": "https://www.redhat.com"
		},
		"references": [
			{
				"category": "self",
				"summary": "https://access.redhat.com/errata/RHSA-2019:3590",
				"url": "https://access.redhat.com/errata/RHSA-2019:3590"
			},
			{
				"category": "external",
				"summary": "https://access.redhat.com/security/updates/classification/#moderate",
				"url": "https://access.redhat.com/security/updates/classification/#moderate"
			},
			{
				"category": "external",
				"summary": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/8.1_release_notes/",
				"url": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/8.1_release_notes/"
			},
			{
				"category": "external",
				"summary": "1700824",
				"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1700824"
			},
			{
				"category": "external",
				"summary": "1702473",
				"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1702473"
			},
			{
				"category": "self",
				"summary": "Canonical URL",
				"url": "https://access.redhat.com/security/data/csaf/v2/advisories/2019/rhsa-2019_3590.json"
			}
		],
		"title": "Red Hat Security Advisory: python-urllib3 security update",
		"tracking": {
			"current_release_date": "2024-09-18T04:10:43+00:00",
			"generator": {
				"date": "2024-09-18T04:10:43+00:00",
				"engine": {
					"name": "Red Hat SDEngine",
					"version": "3.33.3"
				}
			},
			"id": "RHSA-2019:3590",
			"initial_release_date": "2019-11-05T21:14:59+00:00",
			"revision_history": [
				{
					"date": "2019-11-05T21:14:59+00:00",
					"number": "1",
					"summary": "Initial version"
				},
				{
					"date": "2019-11-05T21:14:59+00:00",
					"number": "2",
					"summary": "Last updated version"
				},
				{
					"date": "2024-09-18T04:10:43+00:00",
					"number": "3",
					"summary": "Last generated version"
				}
			],
			"status": "final",
			"version": "3"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_name",
								"name": "Red Hat Enterprise Linux BaseOS (v. 8)",
								"product": {
									"name": "Red Hat Enterprise Linux BaseOS (v. 8)",
									"product_id": "BaseOS-8.1.0",
									"product_identification_helper": {
										"cpe": "cpe:/o:redhat:enterprise_linux:8::baseos"
									}
								}
							}
						],
						"category": "product_family",
						"name": "Red Hat Enterprise Linux"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-urllib3-0:1.24.2-2.el8.src",
								"product": {
									"name": "python-urllib3-0:1.24.2-2.el8.src",
									"product_id": "python-urllib3-0:1.24.2-2.el8.src",
									"product_identification_helper": {
										"purl": "pkg:rpm/redhat/python-urllib3@1.24.2-2.el8?arch=src"
									}
								}
							}
						],
						"category": "architecture",
						"name": "src"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python3-urllib3-0:1.24.2-2.el8.noarch",
								"product": {
									"name": "python3-urllib3-0:1.24.2-2.el8.noarch",
									"product_id": "python3-urllib3-0:1.24.2-2.el8.noarch",
									"product_identification_helper": {
										"purl": "pkg:rpm/redhat/python3-urllib3@1.24.2-2.el8?arch=noarch"
									}
								}
							}
						],
						"category": "architecture",
						"name": "noarch"
					}
				],
				"category": "vendor",
				"name": "Red Hat"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-urllib3-0:1.24.2-2.el8.src as a component of Red Hat Enterprise Linux BaseOS (v. 8)",
					"product_id": "BaseOS-8.1.0:python-urllib3-0:1.24.2-2.el8.src"
				},
				"product_reference": "python-urllib3-0:1.24.2-2.el8.src",
				"relates_to_product_reference": "BaseOS-8.1.0"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python3-urllib3-0:1.24.2-2.el8.noarch as a component of Red Hat Enterprise Linux BaseOS (v. 8)",
					"product_id": "BaseOS-8.1.0:python3-urllib3-0:1.24.2-2.el8.noarch"
				},
				"product_reference": "python3-urllib3-0:1.24.2-2.el8.noarch",
				"relates_to_product_reference": "BaseOS-8.1.0"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2019-11236",
			"cwe": {
				"id": "CWE-113",
				"name": "Improper Neutralization of CRLF Sequences in HTTP Headers ('HTTP Request/Response Splitting')"
			},
			"discovery_date": "2019-04-15T00:00:00+00:00",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "1700824"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "In the urllib3 library through 1.24.1 for Python, CRLF injection is possible if the attacker controls the request parameter.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "python-urllib3: CRLF injection due to not encoding the '\\r\\n' sequence leading to possible attack on internal service",
					"title": "Vulnerability summary"
				},
				{
					"category": "other",
					"text": "This issue affects the version of python-urllib3 shipped with Red Hat Gluster Storage 3, as it is vulnerable to CRLF injection.\n\nRed Hat Satellite 6.2 is on Maintenance Support 2 phase, hence only selected critical and important issues will be fixed. Please refer to Red Hat Satellite Product Life Cycle page for more information.\n\nIn Red Hat OpenStack Platform 13, because the flaw has a lower impact and the fix would require a substantial amount of development, no update will be provided at this time for the RHOSP python-urllib3 package.",
					"title": "Statement"
				},
				{
					"category": "general",
					"text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
					"title": "CVSS score applicability"
				}
			],
			"product_status": {
				"fixed": [
					"BaseOS-8.1.0:python-urllib3-0:1.24.2-2.el8.src",
					"BaseOS-8.1.0:python3-urllib3-0:1.24.2-2.el8.noarch"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2019-11236"
				},
				{
					"category": "external",
					"summary": "RHBZ#1700824",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1700824"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2019-11236",
					"url": "https://www.cve.org/CVERecord?id=CVE-2019-11236"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2019-11236",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2019-11236"
				}
			],
			"release_date": "2019-03-13T00:00:00+00:00",
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "For details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258",
					"product_ids": [
						"BaseOS-8.1.0:python-urllib3-0:1.24.2-2.el8.src",
						"BaseOS-8.1.0:python3-urllib3-0:1.24.2-2.el8.noarch"
					],
					"restart_required": {
						"category": "none"
					},
					"url": "https://access.redhat.com/errata/RHSA-2019:3590"
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"attackComplexity": "LOW",
						"attackVector": "NETWORK",
						"availabilityImpact": "NONE",
						"baseScore": 6.5,
						"baseSeverity": "MEDIUM",
						"confidentialityImpact": "LOW",
						"integrityImpact": "LOW",
						"privilegesRequired": "NONE",
						"scope": "UNCHANGED",
						"userInteraction": "NONE",
						"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
						"version": "3.0"
					},
					"products": [
						"BaseOS-8.1.0:python-urllib3-0:1.24.2-2.el8.src",
						"BaseOS-8.1.0:python3-urllib3-0:1.24.2-2.el8.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Moderate"
				}
			],
			"title": "python-urllib3: CRLF injection due to not encoding the '\\r\\n' sequence leading to possible attack on internal service"
		},
		{
			"cve": "CVE-2019-11324",
			"cwe": {
				"id": "CWE-295",
				"name": "Improper Certificate Validation"
			},
			"discovery_date": "2019-04-18T00:00:00+00:00",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "1702473"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "The urllib3 library before 1.24.2 for Python mishandles certain cases where the desired set of CA certificates is different from the OS store of CA certificates, which results in SSL connections succeeding in situations where a verification failure is the correct outcome. This is related to use of the ssl_context, ca_certs, or ca_certs_dir argument.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "python-urllib3: Certification mishandle when error should be thrown",
					"title": "Vulnerability summary"
				},
				{
					"category": "other",
					"text": "This issue did not affect the versions of python-urllib3 as shipped with Red Hat Enterprise Linux 6, and 7 as the older code shipped there did not load the system certificates.\n\nRed Hat Satellite 6.2 is on Maintenance Support 2 phase, hence only selected Critical and Important issues will be fixed. Please refer to Red Hat Satellite Product Life Cycle page for more information.\n\nIn Red Hat OpenStack Platform 13, because the flaw has a lower impact and the fix would require a substantial amount of development, no update will be provided at this time for the RHOSP python-urllib3 package.",
					"title": "Statement"
				},
				{
					"category": "general",
					"text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
					"title": "CVSS score applicability"
				}
			],
			"product_status": {
				"fixed": [
					"BaseOS-8.1.0:python-urllib3-0:1.24.2-2.el8.src",
					"BaseOS-8.1.0:python3-urllib3-0:1.24.2-2.el8.noarch"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2019-11324"
				},
				{
					"category": "external",
					"summary": "RHBZ#1702473",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1702473"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2019-11324",
					"url": "https://www.cve.org/CVERecord?id=CVE-2019-11324"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2019-11324",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2019-11324"
				},
				{
					"category": "external",
					"summary": "https://www.openwall.com/lists/oss-security/2019/04/17/3",
					"url": "https://www.openwall.com/lists/oss-security/2019/04/17/3"
				}
			],
			"release_date": "2019-04-17T00:00:00+00:00",
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "For details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258",
					"product_ids": [
						"BaseOS-8.1.0:python-urllib3-0:1.24.2-2.el8.src",
						"BaseOS-8.1.0:python3-urllib3-0:1.24.2-2.el8.noarch"
					],
					"restart_required": {
						"category": "none"
					},
					"url": "https://access.redhat.com/errata/RHSA-2019:3590"
				},
				{
					"category": "workaround",
					"details": "The urllib3 package is used by elastic-curator, which is deployed in the ose-logging-curator, and used by the optional logging feature in OpenShift Container Platform (OCP). Therefore OCP 3.11 users can mitigate this issue by not deploying and using the Curator logging feature. \n\nIn OCP 4 urllib3 is also used by several Ansible Play Book images built with the Operator SDK and available for installation in OCP 4 including openshift-enterprise-ansible-operator and ose-metering-ansible-operator. Therefore those operators should not be deployed in order to mitigate this issue in OCP 4.",
					"product_ids": [
						"BaseOS-8.1.0:python-urllib3-0:1.24.2-2.el8.src",
						"BaseOS-8.1.0:python3-urllib3-0:1.24.2-2.el8.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"attackComplexity": "LOW",
						"attackVector": "NETWORK",
						"availabilityImpact": "NONE",
						"baseScore": 7.5,
						"baseSeverity": "HIGH",
						"confidentialityImpact": "NONE",
						"integrityImpact": "HIGH",
						"privilegesRequired": "NONE",
						"scope": "UNCHANGED",
						"userInteraction": "NONE",
						"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
						"version": "3.0"
					},
					"products": [
						"BaseOS-8.1.0:python-urllib3-0:1.24.2-2.el8.src",
						"BaseOS-8.1.0:python3-urllib3-0:1.24.2-2.el8.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Moderate"
				}
			],
			"title": "python-urllib3: Certification mishandle when error should be thrown"
		}
	]
}
