{
	"document": {
		"aggregate_severity": {
			"namespace": "https://access.redhat.com/security/updates/classification/",
			"text": "Moderate"
		},
		"category": "csaf_vex",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright Â© Red Hat, Inc. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "Updated python-keystoneclient packages that fix one security issue are now\navailable for Red Hat Enterprise Linux OpenStack Platform 4.0.\n\nRed Hat Product Security has rated this update as having Moderate security\nimpact. A Common Vulnerability Scoring System (CVSS) base score, which\ngives a detailed severity rating, is available from the CVE link in the\nReferences section.",
				"title": "Topic"
			},
			{
				"category": "general",
				"text": "Python-keystoneclient is a client library and a command line utility for\ninteracting with the OpenStack Identity API. The OpenStack Identity\nauth_token middleware component handles the authentication of tokens\nwith keystone.\n\nIt was found that python-keystoneclient treated all settings in paste.ini\nfiles as string types. If the \"insecure\" option were set to any value in a\npaste.ini configuration file, it would be evaluated as true, resulting in\nTLS connections being vulnerable to man-in-the-middle attacks.\n(CVE-2014-7144)\n\nNote that when the \"insecure\" option was not set in paste.ini, it evaluated\nto false, and verification was performed.\n\nAll python-keystoneclient users are advised to upgrade to these updated\npackages, which correct this issue. After installing this update, all\nOpenStack services using auth_token must be restarted for this update to\ntake effect.",
				"title": "Details"
			},
			{
				"category": "legal_disclaimer",
				"text": "This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original.",
				"title": "Terms of Use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://access.redhat.com/security/team/contact/",
			"issuing_authority": "Red Hat Product Security is responsible for vulnerability handling across all Red Hat offerings.",
			"name": "Red Hat Product Security",
			"namespace": "https://www.redhat.com"
		},
		"references": [
			{
				"category": "self",
				"summary": "https://access.redhat.com/errata/RHSA-2015:0020",
				"url": "https://access.redhat.com/errata/RHSA-2015:0020"
			},
			{
				"category": "external",
				"summary": "https://access.redhat.com/security/updates/classification/#moderate",
				"url": "https://access.redhat.com/security/updates/classification/#moderate"
			},
			{
				"category": "external",
				"summary": "1143808",
				"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1143808"
			},
			{
				"category": "self",
				"summary": "Canonical URL",
				"url": "https://access.redhat.com/security/data/csaf/v2/advisories/2015/rhsa-2015_0020.json"
			}
		],
		"title": "Red Hat Security Advisory: python-keystoneclient security update",
		"tracking": {
			"current_release_date": "2024-04-21T03:42:26+00:00",
			"generator": {
				"date": "2024-04-21T03:42:26+00:00",
				"engine": {
					"name": "Red Hat SDEngine",
					"version": "3.29.1"
				}
			},
			"id": "RHSA-2015:0020",
			"initial_release_date": "2015-01-08T18:05:03+00:00",
			"revision_history": [
				{
					"date": "2015-01-08T18:05:03+00:00",
					"number": "1",
					"summary": "Initial version"
				},
				{
					"date": "2015-01-08T18:05:03+00:00",
					"number": "2",
					"summary": "Last updated version"
				},
				{
					"date": "2024-04-21T03:42:26+00:00",
					"number": "3",
					"summary": "Last generated version"
				}
			],
			"status": "final",
			"version": "3"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_name",
								"name": "Red Hat Enterprise Linux OpenStack Platform 4.0",
								"product": {
									"name": "Red Hat Enterprise Linux OpenStack Platform 4.0",
									"product_id": "6Server-RHOS-4.0",
									"product_identification_helper": {
										"cpe": "cpe:/a:redhat:openstack:4::el6"
									}
								}
							}
						],
						"category": "product_family",
						"name": "Red Hat OpenStack Platform"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-keystoneclient-1:0.7.1-5.el6ost.src",
								"product": {
									"name": "python-keystoneclient-1:0.7.1-5.el6ost.src",
									"product_id": "python-keystoneclient-1:0.7.1-5.el6ost.src",
									"product_identification_helper": {
										"purl": "pkg:rpm/redhat/python-keystoneclient@0.7.1-5.el6ost?arch=src&epoch=1"
									}
								}
							}
						],
						"category": "architecture",
						"name": "src"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-keystoneclient-1:0.7.1-5.el6ost.noarch",
								"product": {
									"name": "python-keystoneclient-1:0.7.1-5.el6ost.noarch",
									"product_id": "python-keystoneclient-1:0.7.1-5.el6ost.noarch",
									"product_identification_helper": {
										"purl": "pkg:rpm/redhat/python-keystoneclient@0.7.1-5.el6ost?arch=noarch&epoch=1"
									}
								}
							},
							{
								"category": "product_version",
								"name": "python-keystoneclient-doc-1:0.7.1-5.el6ost.noarch",
								"product": {
									"name": "python-keystoneclient-doc-1:0.7.1-5.el6ost.noarch",
									"product_id": "python-keystoneclient-doc-1:0.7.1-5.el6ost.noarch",
									"product_identification_helper": {
										"purl": "pkg:rpm/redhat/python-keystoneclient-doc@0.7.1-5.el6ost?arch=noarch&epoch=1"
									}
								}
							}
						],
						"category": "architecture",
						"name": "noarch"
					}
				],
				"category": "vendor",
				"name": "Red Hat"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-keystoneclient-1:0.7.1-5.el6ost.noarch as a component of Red Hat Enterprise Linux OpenStack Platform 4.0",
					"product_id": "6Server-RHOS-4.0:python-keystoneclient-1:0.7.1-5.el6ost.noarch"
				},
				"product_reference": "python-keystoneclient-1:0.7.1-5.el6ost.noarch",
				"relates_to_product_reference": "6Server-RHOS-4.0"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-keystoneclient-1:0.7.1-5.el6ost.src as a component of Red Hat Enterprise Linux OpenStack Platform 4.0",
					"product_id": "6Server-RHOS-4.0:python-keystoneclient-1:0.7.1-5.el6ost.src"
				},
				"product_reference": "python-keystoneclient-1:0.7.1-5.el6ost.src",
				"relates_to_product_reference": "6Server-RHOS-4.0"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-keystoneclient-doc-1:0.7.1-5.el6ost.noarch as a component of Red Hat Enterprise Linux OpenStack Platform 4.0",
					"product_id": "6Server-RHOS-4.0:python-keystoneclient-doc-1:0.7.1-5.el6ost.noarch"
				},
				"product_reference": "python-keystoneclient-doc-1:0.7.1-5.el6ost.noarch",
				"relates_to_product_reference": "6Server-RHOS-4.0"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2014-7144",
			"cwe": {
				"id": "CWE-295",
				"name": "Improper Certificate Validation"
			},
			"discovery_date": "2014-09-17T00:00:00+00:00",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "1143808"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "It was found that python-keystoneclient treated all settings in paste.ini files as string types. If the \"insecure\" option were set to any value in a paste.ini configuration file, it would be evaluated as true, resulting in TLS connections being vulnerable to man-in-the-middle attacks.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "python-keystoneclient: TLS certificate verification disabled",
					"title": "Vulnerability summary"
				},
				{
					"category": "general",
					"text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
					"title": "CVSS score applicability"
				}
			],
			"product_status": {
				"fixed": [
					"6Server-RHOS-4.0:python-keystoneclient-1:0.7.1-5.el6ost.noarch",
					"6Server-RHOS-4.0:python-keystoneclient-1:0.7.1-5.el6ost.src",
					"6Server-RHOS-4.0:python-keystoneclient-doc-1:0.7.1-5.el6ost.noarch"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2014-7144"
				},
				{
					"category": "external",
					"summary": "RHBZ#1143808",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1143808"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2014-7144",
					"url": "https://www.cve.org/CVERecord?id=CVE-2014-7144"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2014-7144",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2014-7144"
				}
			],
			"release_date": "2014-08-06T00:00:00+00:00",
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "Before applying this update, make sure all previously released errata\nrelevant to your system have been applied.\n\nThis update is available via the Red Hat Network. Details on how to\nuse the Red Hat Network to apply this update are available at\nhttps://access.redhat.com/articles/11258",
					"product_ids": [
						"6Server-RHOS-4.0:python-keystoneclient-1:0.7.1-5.el6ost.noarch",
						"6Server-RHOS-4.0:python-keystoneclient-1:0.7.1-5.el6ost.src",
						"6Server-RHOS-4.0:python-keystoneclient-doc-1:0.7.1-5.el6ost.noarch"
					],
					"restart_required": {
						"category": "none"
					},
					"url": "https://access.redhat.com/errata/RHSA-2015:0020"
				}
			],
			"scores": [
				{
					"cvss_v2": {
						"accessComplexity": "MEDIUM",
						"accessVector": "NETWORK",
						"authentication": "NONE",
						"availabilityImpact": "NONE",
						"baseScore": 4.3,
						"confidentialityImpact": "NONE",
						"integrityImpact": "PARTIAL",
						"vectorString": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
						"version": "2.0"
					},
					"products": [
						"6Server-RHOS-4.0:python-keystoneclient-1:0.7.1-5.el6ost.noarch",
						"6Server-RHOS-4.0:python-keystoneclient-1:0.7.1-5.el6ost.src",
						"6Server-RHOS-4.0:python-keystoneclient-doc-1:0.7.1-5.el6ost.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Moderate"
				}
			],
			"title": "python-keystoneclient: TLS certificate verification disabled"
		}
	]
}
