{
	"document": {
		"aggregate_severity": {
			"namespace": "https://access.redhat.com/security/updates/classification/",
			"text": "Moderate"
		},
		"category": "csaf_vex",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright Â© Red Hat, Inc. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "An update for python-django20 is now available for Red Hat OpenStack\nPlatform 16.2 (Train).\n\nRed Hat Product Security has rated this update as having a security impact\nof Moderate. A Common Vulnerability Scoring System (CVSS) base score, which\ngives a detailed severity rating, is available for each vulnerability from\nthe CVE link(s) in the References section.",
				"title": "Topic"
			},
			{
				"category": "general",
				"text": "Security Fix(es):\n\n* Potential directory-traversal via archive.extract() (CVE-2021-3281)\n\n* Potential directory traversal via ``admindocs`` (CVE-2021-33203)\n\n* Possible indeterminate SSRF RFI and LFI attacks since validators accepted\nleading zeros in IPv4 addresses (CVE-2021-33571)\n\nFor more details about the security issue(s), including the impact, a CVSS\nscore, acknowledgments, and other related information, refer to the CVE\npage listed in the References section.",
				"title": "Details"
			},
			{
				"category": "legal_disclaimer",
				"text": "This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original.",
				"title": "Terms of Use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://access.redhat.com/security/team/contact/",
			"issuing_authority": "Red Hat Product Security is responsible for vulnerability handling across all Red Hat offerings.",
			"name": "Red Hat Product Security",
			"namespace": "https://www.redhat.com"
		},
		"references": [
			{
				"category": "self",
				"summary": "https://access.redhat.com/errata/RHSA-2021:3490",
				"url": "https://access.redhat.com/errata/RHSA-2021:3490"
			},
			{
				"category": "external",
				"summary": "https://access.redhat.com/security/updates/classification/#moderate",
				"url": "https://access.redhat.com/security/updates/classification/#moderate"
			},
			{
				"category": "external",
				"summary": "1919969",
				"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1919969"
			},
			{
				"category": "external",
				"summary": "1937284",
				"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1937284"
			},
			{
				"category": "external",
				"summary": "1966251",
				"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1966251"
			},
			{
				"category": "external",
				"summary": "1966253",
				"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1966253"
			},
			{
				"category": "self",
				"summary": "Canonical URL",
				"url": "https://access.redhat.com/security/data/csaf/v2/advisories/2021/rhsa-2021_3490.json"
			}
		],
		"title": "Red Hat Security Advisory: Red Hat OpenStack Platform 16.2 (python-django20) security update",
		"tracking": {
			"current_release_date": "2024-08-15T09:09:19+00:00",
			"generator": {
				"date": "2024-08-15T09:09:19+00:00",
				"engine": {
					"name": "Red Hat SDEngine",
					"version": "3.32.0"
				}
			},
			"id": "RHSA-2021:3490",
			"initial_release_date": "2021-09-15T13:41:11+00:00",
			"revision_history": [
				{
					"date": "2021-09-15T13:41:11+00:00",
					"number": "1",
					"summary": "Initial version"
				},
				{
					"date": "2021-09-15T13:41:11+00:00",
					"number": "2",
					"summary": "Last updated version"
				},
				{
					"date": "2024-08-15T09:09:19+00:00",
					"number": "3",
					"summary": "Last generated version"
				}
			],
			"status": "final",
			"version": "3"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_name",
								"name": "Red Hat OpenStack Platform 16.2",
								"product": {
									"name": "Red Hat OpenStack Platform 16.2",
									"product_id": "8Base-RHOS-16.2",
									"product_identification_helper": {
										"cpe": "cpe:/a:redhat:openstack:16.2::el8"
									}
								}
							}
						],
						"category": "product_family",
						"name": "Red Hat OpenStack Platform"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-django20-0:2.0.13-16.el8ost.1.src",
								"product": {
									"name": "python-django20-0:2.0.13-16.el8ost.1.src",
									"product_id": "python-django20-0:2.0.13-16.el8ost.1.src",
									"product_identification_helper": {
										"purl": "pkg:rpm/redhat/python-django20@2.0.13-16.el8ost.1?arch=src"
									}
								}
							}
						],
						"category": "architecture",
						"name": "src"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python3-django20-0:2.0.13-16.el8ost.1.noarch",
								"product": {
									"name": "python3-django20-0:2.0.13-16.el8ost.1.noarch",
									"product_id": "python3-django20-0:2.0.13-16.el8ost.1.noarch",
									"product_identification_helper": {
										"purl": "pkg:rpm/redhat/python3-django20@2.0.13-16.el8ost.1?arch=noarch"
									}
								}
							}
						],
						"category": "architecture",
						"name": "noarch"
					}
				],
				"category": "vendor",
				"name": "Red Hat"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-django20-0:2.0.13-16.el8ost.1.src as a component of Red Hat OpenStack Platform 16.2",
					"product_id": "8Base-RHOS-16.2:python-django20-0:2.0.13-16.el8ost.1.src"
				},
				"product_reference": "python-django20-0:2.0.13-16.el8ost.1.src",
				"relates_to_product_reference": "8Base-RHOS-16.2"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python3-django20-0:2.0.13-16.el8ost.1.noarch as a component of Red Hat OpenStack Platform 16.2",
					"product_id": "8Base-RHOS-16.2:python3-django20-0:2.0.13-16.el8ost.1.noarch"
				},
				"product_reference": "python3-django20-0:2.0.13-16.el8ost.1.noarch",
				"relates_to_product_reference": "8Base-RHOS-16.2"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2021-3281",
			"cwe": {
				"id": "CWE-22",
				"name": "Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')"
			},
			"discovery_date": "2021-01-25T00:00:00+00:00",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "1919969"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "A flaw was found in django where the`django.utils.archive.extract()` function, used by `startapp --template` and `startproject --template`, allowed directory-traversal via an archive with absolute paths or relative paths with dot segments.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "django: Potential directory-traversal via archive.extract()",
					"title": "Vulnerability summary"
				},
				{
					"category": "other",
					"text": "The following products ship affected version of python-django, however the vulnerable function archive.extract() is currently not used in any part of the product and hence this issue has been rated as having a security impact of Low:\n* Red Hat Gluster Storage 3\n* Red Hat Update Infrastructure 3\n\nBecause the flaw's impact is lower and Red Hat OpenStack Platform 13 will be retiring soon, no update will be provided at this time for the RHOSP13 python-django package.",
					"title": "Statement"
				},
				{
					"category": "general",
					"text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
					"title": "CVSS score applicability"
				}
			],
			"product_status": {
				"fixed": [
					"8Base-RHOS-16.2:python-django20-0:2.0.13-16.el8ost.1.src",
					"8Base-RHOS-16.2:python3-django20-0:2.0.13-16.el8ost.1.noarch"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2021-3281"
				},
				{
					"category": "external",
					"summary": "RHBZ#1919969",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1919969"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2021-3281",
					"url": "https://www.cve.org/CVERecord?id=CVE-2021-3281"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2021-3281",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2021-3281"
				}
			],
			"release_date": "2021-02-01T10:00:00+00:00",
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "For details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258",
					"product_ids": [
						"8Base-RHOS-16.2:python-django20-0:2.0.13-16.el8ost.1.src",
						"8Base-RHOS-16.2:python3-django20-0:2.0.13-16.el8ost.1.noarch"
					],
					"restart_required": {
						"category": "none"
					},
					"url": "https://access.redhat.com/errata/RHSA-2021:3490"
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"attackComplexity": "LOW",
						"attackVector": "NETWORK",
						"availabilityImpact": "NONE",
						"baseScore": 5.3,
						"baseSeverity": "MEDIUM",
						"confidentialityImpact": "NONE",
						"integrityImpact": "LOW",
						"privilegesRequired": "NONE",
						"scope": "UNCHANGED",
						"userInteraction": "NONE",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
						"version": "3.1"
					},
					"products": [
						"8Base-RHOS-16.2:python-django20-0:2.0.13-16.el8ost.1.src",
						"8Base-RHOS-16.2:python3-django20-0:2.0.13-16.el8ost.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Moderate"
				}
			],
			"title": "django: Potential directory-traversal via archive.extract()"
		},
		{
			"cve": "CVE-2021-33203",
			"cwe": {
				"id": "CWE-22",
				"name": "Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')"
			},
			"discovery_date": "2021-05-26T00:00:00+00:00",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "1966251"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "A flaw was found in django. Staff members could use the :mod:`~django.contrib.admindocs` ``TemplateDetailView`` view to check the existence of arbitrary files. Additionally, if (and only if) the default admindocs templates have been customized by the developers to also expose the file contents, then not only the existence but also the file contents would have been exposed. The highest threat from this vulnerability is to data confidentiality.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "django: Potential directory traversal via ``admindocs``",
					"title": "Vulnerability summary"
				},
				{
					"category": "other",
					"text": "Red Hat Update Infrastructure is in maintenance phase and we will not be fixing Medium/Low impact security bugs. Reference: https://access.redhat.com/support/policy/updates/rhui\n\nIn Red Hat OpenStack Platform 13, because the flaw has a lower impact and the fix would require a substantial amount of development, no update will be provided at this time for the RHOSP python-django package.",
					"title": "Statement"
				},
				{
					"category": "general",
					"text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
					"title": "CVSS score applicability"
				}
			],
			"product_status": {
				"fixed": [
					"8Base-RHOS-16.2:python-django20-0:2.0.13-16.el8ost.1.src",
					"8Base-RHOS-16.2:python3-django20-0:2.0.13-16.el8ost.1.noarch"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2021-33203"
				},
				{
					"category": "external",
					"summary": "RHBZ#1966251",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1966251"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2021-33203",
					"url": "https://www.cve.org/CVERecord?id=CVE-2021-33203"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2021-33203",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2021-33203"
				},
				{
					"category": "external",
					"summary": "https://www.djangoproject.com/weblog/2021/jun/02/security-releases/",
					"url": "https://www.djangoproject.com/weblog/2021/jun/02/security-releases/"
				}
			],
			"release_date": "2021-06-02T00:00:00+00:00",
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "For details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258",
					"product_ids": [
						"8Base-RHOS-16.2:python-django20-0:2.0.13-16.el8ost.1.src",
						"8Base-RHOS-16.2:python3-django20-0:2.0.13-16.el8ost.1.noarch"
					],
					"restart_required": {
						"category": "none"
					},
					"url": "https://access.redhat.com/errata/RHSA-2021:3490"
				},
				{
					"category": "workaround",
					"details": "Mitigation for this issue is either not available or the currently available options do not meet the Red Hat Product Security criteria comprising ease of use and deployment, applicability to widespread installation base or stability.",
					"product_ids": [
						"8Base-RHOS-16.2:python-django20-0:2.0.13-16.el8ost.1.src",
						"8Base-RHOS-16.2:python3-django20-0:2.0.13-16.el8ost.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"attackComplexity": "LOW",
						"attackVector": "NETWORK",
						"availabilityImpact": "NONE",
						"baseScore": 4.9,
						"baseSeverity": "MEDIUM",
						"confidentialityImpact": "HIGH",
						"integrityImpact": "NONE",
						"privilegesRequired": "HIGH",
						"scope": "UNCHANGED",
						"userInteraction": "NONE",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:N/A:N",
						"version": "3.1"
					},
					"products": [
						"8Base-RHOS-16.2:python-django20-0:2.0.13-16.el8ost.1.src",
						"8Base-RHOS-16.2:python3-django20-0:2.0.13-16.el8ost.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Moderate"
				}
			],
			"title": "django: Potential directory traversal via ``admindocs``"
		},
		{
			"cve": "CVE-2021-33571",
			"cwe": {
				"id": "CWE-918",
				"name": "Server-Side Request Forgery (SSRF)"
			},
			"discovery_date": "2021-05-26T00:00:00+00:00",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "1966253"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "A flaw was found in django. Leading zeros in octal literals aren't prohibited in IP addresses. If you used such values you could suffer from indeterminate SSRF, RFI, and LFI attacks. The highest threat from this vulnerability is to data integrity.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "django: Possible indeterminate SSRF, RFI, and LFI attacks since validators accepted leading zeros in IPv4 addresses",
					"title": "Vulnerability summary"
				},
				{
					"category": "other",
					"text": "Red Hat Update Infrastructure is in maintenance phase and we will not be fixing Medium/Low impact security bugs. Reference: https://access.redhat.com/support/policy/updates/rhui\n\nIn Red Hat OpenStack Platform 13, because the flaw has a lower impact and the fix would require a substantial amount of development, no update will be provided at this time for the RHOSP python-django package.",
					"title": "Statement"
				},
				{
					"category": "general",
					"text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
					"title": "CVSS score applicability"
				}
			],
			"product_status": {
				"fixed": [
					"8Base-RHOS-16.2:python-django20-0:2.0.13-16.el8ost.1.src",
					"8Base-RHOS-16.2:python3-django20-0:2.0.13-16.el8ost.1.noarch"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2021-33571"
				},
				{
					"category": "external",
					"summary": "RHBZ#1966253",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1966253"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2021-33571",
					"url": "https://www.cve.org/CVERecord?id=CVE-2021-33571"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2021-33571",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2021-33571"
				},
				{
					"category": "external",
					"summary": "https://www.djangoproject.com/weblog/2021/jun/02/security-releases/",
					"url": "https://www.djangoproject.com/weblog/2021/jun/02/security-releases/"
				}
			],
			"release_date": "2021-06-02T00:00:00+00:00",
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "For details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258",
					"product_ids": [
						"8Base-RHOS-16.2:python-django20-0:2.0.13-16.el8ost.1.src",
						"8Base-RHOS-16.2:python3-django20-0:2.0.13-16.el8ost.1.noarch"
					],
					"restart_required": {
						"category": "none"
					},
					"url": "https://access.redhat.com/errata/RHSA-2021:3490"
				},
				{
					"category": "workaround",
					"details": "Mitigation for this issue is either not available or the currently available options do not meet the Red Hat Product Security criteria comprising ease of use and deployment, applicability to widespread installation base or stability.",
					"product_ids": [
						"8Base-RHOS-16.2:python-django20-0:2.0.13-16.el8ost.1.src",
						"8Base-RHOS-16.2:python3-django20-0:2.0.13-16.el8ost.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"attackComplexity": "LOW",
						"attackVector": "NETWORK",
						"availabilityImpact": "NONE",
						"baseScore": 7.5,
						"baseSeverity": "HIGH",
						"confidentialityImpact": "NONE",
						"integrityImpact": "HIGH",
						"privilegesRequired": "NONE",
						"scope": "UNCHANGED",
						"userInteraction": "NONE",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
						"version": "3.1"
					},
					"products": [
						"8Base-RHOS-16.2:python-django20-0:2.0.13-16.el8ost.1.src",
						"8Base-RHOS-16.2:python3-django20-0:2.0.13-16.el8ost.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Moderate"
				}
			],
			"title": "django: Possible indeterminate SSRF, RFI, and LFI attacks since validators accepted leading zeros in IPv4 addresses"
		}
	]
}
