{
	"document": {
		"aggregate_severity": {
			"namespace": "https://access.redhat.com/security/updates/classification/",
			"text": "Moderate"
		},
		"category": "csaf_vex",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright Â© Red Hat, Inc. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "Updated Django packages that fix multiple security issues are now available\nfor Red Hat OpenStack Folsom.\n\nThe Red Hat Security Response Team has rated this update as having moderate\nsecurity impact. Common Vulnerability Scoring System (CVSS) base scores,\nwhich give detailed severity ratings, are available for each vulnerability\nfrom the CVE links in the References section.",
				"title": "Topic"
			},
			{
				"category": "general",
				"text": "The Django web framework is used by Horizon, the OpenStack Dashboard, which\nis a web interface for managing OpenStack services.\n\nA denial of service flaw was found in the Extensible Markup Language (XML)\nparser used by Django. A remote attacker could use this flaw to send a\nspecially-crafted request to an Horizon API, causing Horizon to consume an\nexcessive amount of CPU and memory. (CVE-2013-1664)\n\nA flaw was found in the XML parser used by Django. If a remote attacker\nsent a specially-crafted request to an Horizon API, it could cause Horizon\nto connect to external entities, causing a large amount of system load, or\nallow an attacker to read files on the Horizon server that are accessible\nto the user running Horizon. (CVE-2013-1665)\n\nIt was found that the history view in the bundled administrative web\ninterface in Django did not perform permission checks. An authenticated\nuser who can access the web interface could use this flaw to view the\nchanges to objects and data they would otherwise not have access to.\n(CVE-2013-0305)\n\nA flaw was found in the way Django handled formsets. A remote attacker\ncould use this flaw to submit a large number of forms, causing excessive\nmemory consumption. Note: The current version of OpenStack in Red Hat\nOpenStack Folsom does not expose this vulnerability. (CVE-2013-0306)\n\nThis update also includes two hardening fixes to help protect against XML\nentity and HTTP Host header poisoning attacks. (BZ#913039, BZ#913037)\n\nAll users of Horizon are advised to upgrade to these updated packages,\nwhich resolve these issues. After installing the updated packages, the\nhttpd daemon must be restarted (\"service httpd restart\") for the update to\ntake effect.",
				"title": "Details"
			},
			{
				"category": "legal_disclaimer",
				"text": "This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original.",
				"title": "Terms of Use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://access.redhat.com/security/team/contact/",
			"issuing_authority": "Red Hat Product Security is responsible for vulnerability handling across all Red Hat offerings.",
			"name": "Red Hat Product Security",
			"namespace": "https://www.redhat.com"
		},
		"references": [
			{
				"category": "self",
				"summary": "https://access.redhat.com/errata/RHSA-2013:0670",
				"url": "https://access.redhat.com/errata/RHSA-2013:0670"
			},
			{
				"category": "external",
				"summary": "https://access.redhat.com/security/updates/classification/#moderate",
				"url": "https://access.redhat.com/security/updates/classification/#moderate"
			},
			{
				"category": "external",
				"summary": "912982",
				"url": "https://bugzilla.redhat.com/show_bug.cgi?id=912982"
			},
			{
				"category": "external",
				"summary": "913037",
				"url": "https://bugzilla.redhat.com/show_bug.cgi?id=913037"
			},
			{
				"category": "external",
				"summary": "913039",
				"url": "https://bugzilla.redhat.com/show_bug.cgi?id=913039"
			},
			{
				"category": "external",
				"summary": "913041",
				"url": "https://bugzilla.redhat.com/show_bug.cgi?id=913041"
			},
			{
				"category": "external",
				"summary": "913042",
				"url": "https://bugzilla.redhat.com/show_bug.cgi?id=913042"
			},
			{
				"category": "external",
				"summary": "913808",
				"url": "https://bugzilla.redhat.com/show_bug.cgi?id=913808"
			},
			{
				"category": "self",
				"summary": "Canonical URL",
				"url": "https://access.redhat.com/security/data/csaf/v2/advisories/2013/rhsa-2013_0670.json"
			}
		],
		"title": "Red Hat Security Advisory: Django security update",
		"tracking": {
			"current_release_date": "2024-04-21T02:56:11+00:00",
			"generator": {
				"date": "2024-04-21T02:56:11+00:00",
				"engine": {
					"name": "Red Hat SDEngine",
					"version": "3.29.1"
				}
			},
			"id": "RHSA-2013:0670",
			"initial_release_date": "2013-03-21T18:11:00+00:00",
			"revision_history": [
				{
					"date": "2013-03-21T18:11:00+00:00",
					"number": "1",
					"summary": "Initial version"
				},
				{
					"date": "2013-03-21T18:12:01+00:00",
					"number": "2",
					"summary": "Last updated version"
				},
				{
					"date": "2024-04-21T02:56:11+00:00",
					"number": "3",
					"summary": "Last generated version"
				}
			],
			"status": "final",
			"version": "3"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_name",
								"name": "OpenStack Folsom",
								"product": {
									"name": "OpenStack Folsom",
									"product_id": "6Server-Folsom",
									"product_identification_helper": {
										"cpe": "cpe:/a:redhat:openstack:2::el6"
									}
								}
							}
						],
						"category": "product_family",
						"name": "Red Hat OpenStack Platform"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "Django14-0:1.4.4-1.el6ost.noarch",
								"product": {
									"name": "Django14-0:1.4.4-1.el6ost.noarch",
									"product_id": "Django14-0:1.4.4-1.el6ost.noarch",
									"product_identification_helper": {
										"purl": "pkg:rpm/redhat/Django14@1.4.4-1.el6ost?arch=noarch"
									}
								}
							},
							{
								"category": "product_version",
								"name": "Django14-doc-0:1.4.4-1.el6ost.noarch",
								"product": {
									"name": "Django14-doc-0:1.4.4-1.el6ost.noarch",
									"product_id": "Django14-doc-0:1.4.4-1.el6ost.noarch",
									"product_identification_helper": {
										"purl": "pkg:rpm/redhat/Django14-doc@1.4.4-1.el6ost?arch=noarch"
									}
								}
							}
						],
						"category": "architecture",
						"name": "noarch"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "Django14-0:1.4.4-1.el6ost.src",
								"product": {
									"name": "Django14-0:1.4.4-1.el6ost.src",
									"product_id": "Django14-0:1.4.4-1.el6ost.src",
									"product_identification_helper": {
										"purl": "pkg:rpm/redhat/Django14@1.4.4-1.el6ost?arch=src"
									}
								}
							}
						],
						"category": "architecture",
						"name": "src"
					}
				],
				"category": "vendor",
				"name": "Red Hat"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "Django14-0:1.4.4-1.el6ost.noarch as a component of OpenStack Folsom",
					"product_id": "6Server-Folsom:Django14-0:1.4.4-1.el6ost.noarch"
				},
				"product_reference": "Django14-0:1.4.4-1.el6ost.noarch",
				"relates_to_product_reference": "6Server-Folsom"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "Django14-0:1.4.4-1.el6ost.src as a component of OpenStack Folsom",
					"product_id": "6Server-Folsom:Django14-0:1.4.4-1.el6ost.src"
				},
				"product_reference": "Django14-0:1.4.4-1.el6ost.src",
				"relates_to_product_reference": "6Server-Folsom"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "Django14-doc-0:1.4.4-1.el6ost.noarch as a component of OpenStack Folsom",
					"product_id": "6Server-Folsom:Django14-doc-0:1.4.4-1.el6ost.noarch"
				},
				"product_reference": "Django14-doc-0:1.4.4-1.el6ost.noarch",
				"relates_to_product_reference": "6Server-Folsom"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2013-0305",
			"discovery_date": "2013-02-19T00:00:00+00:00",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "913041"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "The administrative interface for Django 1.3.x before 1.3.6, 1.4.x before 1.4.4, and 1.5 before release candidate 2 does not check permissions for the history view, which allows remote authenticated administrators to obtain sensitive object history information.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "Django: Data leakage via admin history log",
					"title": "Vulnerability summary"
				},
				{
					"category": "general",
					"text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
					"title": "CVSS score applicability"
				}
			],
			"product_status": {
				"fixed": [
					"6Server-Folsom:Django14-0:1.4.4-1.el6ost.noarch",
					"6Server-Folsom:Django14-0:1.4.4-1.el6ost.src",
					"6Server-Folsom:Django14-doc-0:1.4.4-1.el6ost.noarch"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2013-0305"
				},
				{
					"category": "external",
					"summary": "RHBZ#913041",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=913041"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2013-0305",
					"url": "https://www.cve.org/CVERecord?id=CVE-2013-0305"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2013-0305",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2013-0305"
				}
			],
			"release_date": "2013-02-19T00:00:00+00:00",
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "Before applying this update, make sure all previously-released errata\nrelevant to your system have been applied.\n\nThis update is available via the Red Hat Network. Details on how to\nuse the Red Hat Network to apply this update are available at\nhttps://access.redhat.com/knowledge/articles/11258",
					"product_ids": [
						"6Server-Folsom:Django14-0:1.4.4-1.el6ost.noarch",
						"6Server-Folsom:Django14-0:1.4.4-1.el6ost.src",
						"6Server-Folsom:Django14-doc-0:1.4.4-1.el6ost.noarch"
					],
					"restart_required": {
						"category": "none"
					},
					"url": "https://access.redhat.com/errata/RHSA-2013:0670"
				}
			],
			"scores": [
				{
					"cvss_v2": {
						"accessComplexity": "LOW",
						"accessVector": "NETWORK",
						"authentication": "SINGLE",
						"availabilityImpact": "NONE",
						"baseScore": 4,
						"confidentialityImpact": "PARTIAL",
						"integrityImpact": "NONE",
						"vectorString": "AV:N/AC:L/Au:S/C:P/I:N/A:N",
						"version": "2.0"
					},
					"products": [
						"6Server-Folsom:Django14-0:1.4.4-1.el6ost.noarch",
						"6Server-Folsom:Django14-0:1.4.4-1.el6ost.src",
						"6Server-Folsom:Django14-doc-0:1.4.4-1.el6ost.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Moderate"
				}
			],
			"title": "Django: Data leakage via admin history log"
		},
		{
			"cve": "CVE-2013-0306",
			"discovery_date": "2013-02-19T00:00:00+00:00",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "913042"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "The form library in Django 1.3.x before 1.3.6, 1.4.x before 1.4.4, and 1.5 before release candidate 2 allows remote attackers to bypass intended resource limits for formsets and cause a denial of service (memory consumption) or trigger server errors via a modified max_num parameter.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "Django: Formset denial-of-service",
					"title": "Vulnerability summary"
				},
				{
					"category": "general",
					"text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
					"title": "CVSS score applicability"
				}
			],
			"product_status": {
				"fixed": [
					"6Server-Folsom:Django14-0:1.4.4-1.el6ost.noarch",
					"6Server-Folsom:Django14-0:1.4.4-1.el6ost.src",
					"6Server-Folsom:Django14-doc-0:1.4.4-1.el6ost.noarch"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2013-0306"
				},
				{
					"category": "external",
					"summary": "RHBZ#913042",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=913042"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2013-0306",
					"url": "https://www.cve.org/CVERecord?id=CVE-2013-0306"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2013-0306",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2013-0306"
				}
			],
			"release_date": "2013-02-19T00:00:00+00:00",
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "Before applying this update, make sure all previously-released errata\nrelevant to your system have been applied.\n\nThis update is available via the Red Hat Network. Details on how to\nuse the Red Hat Network to apply this update are available at\nhttps://access.redhat.com/knowledge/articles/11258",
					"product_ids": [
						"6Server-Folsom:Django14-0:1.4.4-1.el6ost.noarch",
						"6Server-Folsom:Django14-0:1.4.4-1.el6ost.src",
						"6Server-Folsom:Django14-doc-0:1.4.4-1.el6ost.noarch"
					],
					"restart_required": {
						"category": "none"
					},
					"url": "https://access.redhat.com/errata/RHSA-2013:0670"
				}
			],
			"scores": [
				{
					"cvss_v2": {
						"accessComplexity": "LOW",
						"accessVector": "NETWORK",
						"authentication": "NONE",
						"availabilityImpact": "PARTIAL",
						"baseScore": 5,
						"confidentialityImpact": "NONE",
						"integrityImpact": "NONE",
						"vectorString": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
						"version": "2.0"
					},
					"products": [
						"6Server-Folsom:Django14-0:1.4.4-1.el6ost.noarch",
						"6Server-Folsom:Django14-0:1.4.4-1.el6ost.src",
						"6Server-Folsom:Django14-doc-0:1.4.4-1.el6ost.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Moderate"
				}
			],
			"title": "Django: Formset denial-of-service"
		},
		{
			"cve": "CVE-2013-1664",
			"discovery_date": "2013-02-18T00:00:00+00:00",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "913808"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "The XML libraries for Python 3.4, 3.3, 3.2, 3.1, 2.7, and 2.6, as used in OpenStack Keystone Essex, Folsom, and Grizzly; Compute (Nova) Essex and Folsom; Cinder Folsom; Django; and possibly other products allow remote attackers to cause a denial of service (resource consumption and crash) via an XML Entity Expansion (XEE) attack.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "Python xml bindings: Internal entity expansion in Python XML libraries inflicts DoS vulnerabilities",
					"title": "Vulnerability summary"
				},
				{
					"category": "other",
					"text": "This issue affects the versions of python as shipped with Red Hat Enterprise Linux 5, 6 and 7. Red Hat Product Security has rated this issue as having Moderate security impact. This issue is not currently planned to be addressed in future updates.",
					"title": "Statement"
				},
				{
					"category": "general",
					"text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
					"title": "CVSS score applicability"
				}
			],
			"product_status": {
				"fixed": [
					"6Server-Folsom:Django14-0:1.4.4-1.el6ost.noarch",
					"6Server-Folsom:Django14-0:1.4.4-1.el6ost.src",
					"6Server-Folsom:Django14-doc-0:1.4.4-1.el6ost.noarch"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2013-1664"
				},
				{
					"category": "external",
					"summary": "RHBZ#913808",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=913808"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2013-1664",
					"url": "https://www.cve.org/CVERecord?id=CVE-2013-1664"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2013-1664",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2013-1664"
				}
			],
			"release_date": "2013-02-19T00:00:00+00:00",
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "Before applying this update, make sure all previously-released errata\nrelevant to your system have been applied.\n\nThis update is available via the Red Hat Network. Details on how to\nuse the Red Hat Network to apply this update are available at\nhttps://access.redhat.com/knowledge/articles/11258",
					"product_ids": [
						"6Server-Folsom:Django14-0:1.4.4-1.el6ost.noarch",
						"6Server-Folsom:Django14-0:1.4.4-1.el6ost.src",
						"6Server-Folsom:Django14-doc-0:1.4.4-1.el6ost.noarch"
					],
					"restart_required": {
						"category": "none"
					},
					"url": "https://access.redhat.com/errata/RHSA-2013:0670"
				}
			],
			"scores": [
				{
					"cvss_v2": {
						"accessComplexity": "MEDIUM",
						"accessVector": "NETWORK",
						"authentication": "NONE",
						"availabilityImpact": "PARTIAL",
						"baseScore": 4.3,
						"confidentialityImpact": "NONE",
						"integrityImpact": "NONE",
						"vectorString": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
						"version": "2.0"
					},
					"products": [
						"6Server-Folsom:Django14-0:1.4.4-1.el6ost.noarch",
						"6Server-Folsom:Django14-0:1.4.4-1.el6ost.src",
						"6Server-Folsom:Django14-doc-0:1.4.4-1.el6ost.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Moderate"
				}
			],
			"title": "Python xml bindings: Internal entity expansion in Python XML libraries inflicts DoS vulnerabilities"
		},
		{
			"cve": "CVE-2013-1665",
			"discovery_date": "2013-02-18T00:00:00+00:00",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "912982"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "The XML libraries for Python 3.4, 3.3, 3.2, 3.1, 2.7, and 2.6, as used in OpenStack Keystone Essex and Folsom, Django, and possibly other products allow remote attackers to read arbitrary files via an XML external entity declaration in conjunction with an entity reference, aka an XML External Entity (XXE) attack.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "Python xml bindings: External entity expansion in Python XML libraries inflicts potential security flaws and DoS vulnerabilities",
					"title": "Vulnerability summary"
				},
				{
					"category": "other",
					"text": "This issue affects the versions of python as shipped with Red Hat Enterprise Linux 5, 6 and 7. Red Hat Product Security has rated this issue as having Moderate security impact. This issue is not currently planned to be addressed in future updates.",
					"title": "Statement"
				},
				{
					"category": "general",
					"text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
					"title": "CVSS score applicability"
				}
			],
			"product_status": {
				"fixed": [
					"6Server-Folsom:Django14-0:1.4.4-1.el6ost.noarch",
					"6Server-Folsom:Django14-0:1.4.4-1.el6ost.src",
					"6Server-Folsom:Django14-doc-0:1.4.4-1.el6ost.noarch"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2013-1665"
				},
				{
					"category": "external",
					"summary": "RHBZ#912982",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=912982"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2013-1665",
					"url": "https://www.cve.org/CVERecord?id=CVE-2013-1665"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2013-1665",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2013-1665"
				}
			],
			"release_date": "2013-02-19T00:00:00+00:00",
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "Before applying this update, make sure all previously-released errata\nrelevant to your system have been applied.\n\nThis update is available via the Red Hat Network. Details on how to\nuse the Red Hat Network to apply this update are available at\nhttps://access.redhat.com/knowledge/articles/11258",
					"product_ids": [
						"6Server-Folsom:Django14-0:1.4.4-1.el6ost.noarch",
						"6Server-Folsom:Django14-0:1.4.4-1.el6ost.src",
						"6Server-Folsom:Django14-doc-0:1.4.4-1.el6ost.noarch"
					],
					"restart_required": {
						"category": "none"
					},
					"url": "https://access.redhat.com/errata/RHSA-2013:0670"
				}
			],
			"scores": [
				{
					"cvss_v2": {
						"accessComplexity": "MEDIUM",
						"accessVector": "NETWORK",
						"authentication": "NONE",
						"availabilityImpact": "PARTIAL",
						"baseScore": 5.8,
						"confidentialityImpact": "PARTIAL",
						"integrityImpact": "NONE",
						"vectorString": "AV:N/AC:M/Au:N/C:P/I:N/A:P",
						"version": "2.0"
					},
					"products": [
						"6Server-Folsom:Django14-0:1.4.4-1.el6ost.noarch",
						"6Server-Folsom:Django14-0:1.4.4-1.el6ost.src",
						"6Server-Folsom:Django14-doc-0:1.4.4-1.el6ost.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Moderate"
				}
			],
			"title": "Python xml bindings: External entity expansion in Python XML libraries inflicts potential security flaws and DoS vulnerabilities"
		}
	]
}
